#!/bin/sh

source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

xset r rate 300 50

autostart="mpd unclutter redshift bar mpd-mpris"
for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1
