" General
" ======
"" start w/ relative line numbers
set relativenumber

"" 'control+n' to reset highlighting (e.g. after a search or search/replace)
nnoremap <C-n> :nohl<CR>

"" set colorscheme
colorscheme elflord

"" set spaces instead of tabs
set tabstop=4 shiftwidth=4 expandtab
