## Hooks

# case-insensitive search
map global user / '/(?i)' -docstring 'case-insensitive search'
map global user s 's(?i)' -docstring 'case-insensitive select'

# revert breaking changes
map global normal <space> ,
map global normal , <space>
define-command select-or-extend-lines %{
  try %{
    # At least one selection is not full, so select whole lines.
    execute-keys -draft '<a-K>\A^.+\n\z<ret>'
    execute-keys 'x'
  } catch %{
    execute-keys 'J'
  }
}
map global normal 'X' ': select-or-extend-lines<ret>'

# add line numbers
hook global KakBegin .* %{addhl global/ number-lines}

# highlight characters in 81st column
hook global BufCreate .*[.](md|tex) %{
    set buffer autowrap_column 80
    addhl regex ^\V{80}(\V) 1:Error
}
hook global WinCreate .*[.](md|tex|rst) %{
    set buffer autowrap_column 80
    autowrap-enable
}

# add brackets highlighting
hook global KakBegin .* %{addhl global/ show-matching}

# Tmux
hook global RegisterModified '"' %{ nop %sh{ tmux set-buffer "$kak_main_reg_dquote" } }

# colors
colorscheme moonfly

# scroll offset
set global scrolloff 12,0

# tabs
# 4-space tabs
set global indentwidth 4
set global tabstop 4

hook global InsertChar \t %{ try %{
      execute-keys -draft "h<a-h><a-k>\A\h+\z<ret><a-;>;%opt{indentwidth}@"
}}
hook global InsertDelete ' ' %{ try %{
      execute-keys -draft 'h<a-h><a-k>\A\h+\z<ret>i<space><esc><lt>'
}}

# 2-space tabs for json
#hook global BufSetOption filetype=json %{
hook global BufSetOption filetype=(java|json|tex) %{
    set buffer tabstop 2
    set buffer indentwidth 2
}

# tab indents or tab-completes, depending on context
hook global InsertCompletionShow .* %{
    try %{
        # this command temporarily removes cursors preceded by whitespace;
        # if there are no cursors left, it raises an error, does not
        # continue to execute the mapping commands, and the error is eaten
        # by the `try` command so no warning appears.
        execute-keys -draft 'h<a-K>\h<ret>'
        map window insert <tab> <c-n>
        map window insert <s-tab> <c-p>
        hook -once -always window InsertCompletionHide .* %{
            unmap window insert <tab> <c-n>
            unmap window insert <s-tab> <c-p>
        }
    }
}

hook global KakBegin .* %{
    evaluate-commands %sh{
        path="$PWD"
        while [ "$path" != "$HOME" ] && [ "$path" != "/" ]; do
            if [ -e "./tags" ]; then
                printf "%s\n" "set-option -add current ctagsfiles %{$path/tags}"
                break
            else
                cd ..
                path="$PWD"
            fi
        done
    }
}

hook global BufSetOption filetype=python %{
    map global user d 'ifrom pprint import pprint; import ipdb;ipdb.set_trace(context=30)<esc>' -docstring "debug print statement"
}

map global user f '| fmt -w 80<ret>' -docstring 'format selection at 80 columns'

# Plugins
# -------

source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload

plug "kakoune-lsp/kakoune-lsp" do %{
    cargo install --locked --force --path .
} config %{
    set-option global lsp_auto_highlight_references false
    set-option global lsp_auto_show_code_actions false
    set-option global lsp_completion_trigger %{ fail }
    set-option global modelinefmt "%opt{lsp_modeline} %opt{modelinefmt}"

    define-command -override -hidden lsp-handle-progress -params 6 %{
        set-option global lsp_modeline_progress %sh{
            if ! "$6"; then
                printf '{Information}lsp: %s{Default} ' "$2"
            fi
        }
    }

    map global user l ': enter-user-mode lsp<ret>' -docstring 'lsp…'
    map global goto d '<esc>: lsp-definition<ret>' -docstring 'definition'
    map global goto r '<esc>: lsp-references<ret>' -docstring 'references'

    remove-hooks global lsp-filetype-rust
    hook -group lsp-filetype-rust global BufSetOption filetype=rust %{
        set-option buffer lsp_servers %{
            [rust-analyzer]
            root_globs = ["Cargo.toml"]
            single_instance = true
            [rust-analyzer.settings.rust-analyzer]
            checkOnSave = false
            cachePriming.enable = false
        }
    }

    hook global WinSetOption filetype=(json|kotlin|python|rust) %{
        set-option window lsp_hover_anchor false
        echo -debug "Enabling LSP for filtetype %opt{filetype}"
        try %{
            lsp-enable-window
            #lsp-auto-hover-enable
            remove-hooks window lsp-breadcrumbs
            lsp-inline-diagnostics-disable window
            lsp-diagnostic-lines-disable window
        }
    }
}

plug 'delapouite/kakoune-cd' config %{
    # Suggested mapping
    map global user c ': enter-user-mode cd<ret>' -docstring 'cd'
    # Suggested aliases
    alias global cdb change-directory-current-buffer
    alias global cdr change-directory-project-root
    alias global ecd edit-current-buffer-directory
    alias global pwd print-working-directory
}

plug 'delapouite/kakoune-buffers' config %{
    # Suggested mappings
    map global user b ':enter-buffers-mode<ret>'              -docstring 'buffers…'
    map global user B ':enter-user-mode -lock buffers<ret>'   -docstring 'buffers (lock)…'

    # Suggested aliases
    alias global bd delete-buffer
    alias global bf buffer-first
    alias global bl buffer-last
    alias global bo buffer-only
    alias global bo! buffer-only-force
}
