library   : /Users/josiahpohl/.config/beets/library.blb
directory : /Users/josiahpohl/Music/beets_library/
import:
    write              : yes
    copy               : no
    move               : yes
    incremental        : no
    timid              : no
    detail             : yes
    color              : yes
    threaded           : yes
    per_disc_numbering : no
plugins: inline fromfilename duplicates missing bandcamp mbsync ydl
match:
    preferred:
        countries     : ['US']
        media         : ['CD', 'Digital Media|File']
        original_year : yes
item_fields:
    track_title_snake: |
        track_pref = u'0' if track < 10 else u''
        smart_track = u'{tp}{tr}'.format(tp=track_pref, tr=track)
        return u'{tr}-{ti}'.format(tr=smart_track, ti=title.lower().replace(' ', '_'))
paths:
    default   : $albumartist/[$original_year-$original_month] $album/$track_title_snake
    singleton : etc/no-album/$artist/$track_title_snake
    comp      : etc/compilations/[$original_year] $album/$track_title_snake
