#!/usr/bin/env sh

spacebar -m config position           bottom
spacebar -m config height             22
spacebar -m config spacing_left       20
spacebar -m config spacing_right      15
spacebar -m config text_font          "Helvetica Neue:Bold:12.0"
spacebar -m config icon_font          "Font Awesome 5 Free:Regular:12.0"
spacebar -m config background_color   0xff000000
spacebar -m config foreground_color   0xffa8a8a8
spacebar -m config space_icon_color   0xff458588
spacebar -m config power_icon_color   0xffcd950c
spacebar -m config space_icon_strip   1 2 3 4 5 6 7 8 9
spacebar -m config clock_format       "%m/%d/%y %R"

echo "spacebar configuration loaded.."
