#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# spacebar config
SPACEBAR_HEIGHT=$(spacebar -m config height)
yabai -m config external_bar main:0:$SPACEBAR_HEIGHT

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_width          0
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

# rule configuration
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="App Store" manage=off
yabai -m rule --add app="Messages" manage=off
yabai -m rule --add app="Microsoft Teams" manage=off
yabai -m rule --add app="Skype for Business" manage=off
yabai -m rule --add app="Microsoft Remote Desktop" manage=off
yabai -m rule --add app="IntelliJ IDEA CE" manage=off
yabai -m rule --add app="Cyberduck" manage=off


echo "yabai configuration loaded.."
